# SPDK_ROOT_DIR := $(abspath $(CURDIR)/../spdk)
# include $(SPDK_ROOT_DIR)/mk/spdk.common.mk
# include $(SPDK_ROOT_DIR)/mk/spdk.modules.mk

# APP = nvme_opera

# C_SRCS := nvme_opera.c

# SPDK_LIB_LIST = $(SOCK_MODULES_LIST)

# include $(SPDK_ROOT_DIR)/mk/spdk.app.mk



SPDK_ROOT_DIR := $(abspath $(CURDIR)/../spdk/)

APP = nvme_opera
C_SRCS := nvme_opera.c

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
